### ISSUE TITLE
Ensure Argus frontend works well on small screens / mobile

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/Argus-frontend#219]
### Tasks

- [x] Estimate the amount of work needed to ensure Argus frontend mobile friendliness
- [x] Timeslots component/view needs complete/partial rewrite
- [x] Notification profile component(s) needs complete/partial rewrite
- [x] Custom mobile navbar, probably a drop-down bar needs to be added

**Comment by jorgenbele** [comment]
After having a quick look I've discovered the following: (other things might be required as well)

Some components need complete/partial rewrite:
- [ ] Timeslots component/view
- [ ] Notification profile component(s)

And the following needs to be added:
- [ ] Custom mobile navbar, probably a drop-down bar

In addition to the implementation of these features, supporting mobile devices might impact the future development time. To always support mobile will most probably lead to some mobile-friendly design decisions however, which might be good if this will become a larger priority in the future. Luckily we are using the React Material UI framework, which has great support for mobile devices.

**Comment by katsel** [comment]
No point in making time slots and notification profiles mobile friendly while we are still working on it.
