### ISSUE TITLE
Update user manual

### ISSUE THREAD

**Issue by podliashanyk** [Uninett/Argus-frontend#465]
There have been merged PRs that require updates in the MANUAL.md:

- [ ] New _Create ticket_ feature #461 
- [ ] Changed workflow for _Edit ticket_ feature #461 
- [ ] Screenshots with helper text on _bulk updates_ #444 
- [ ] Screenshots for _Severity level_ #442 
- [ ] Specify that timeslots are reusable when working with _Notification profiles_ #415
